### ISSUE TITLE
uiux

### ISSUE THREAD

**Issue by hj0321** [Review-Michelin/Review-Michelin#2]
![스크린샷(7)](https://user-images.githubusercontent.com/71124790/162124147-638b1ec2-f95d-49ea-8fba-126d6fb44120.png)

![스크린샷(8)](https://user-images.githubusercontent.com/71124790/162124166-e8ad2235-ea7b-4545-be77-d51af1e41ea9.png)

![스크린샷(9)](https://user-images.githubusercontent.com/71124790/162124182-a56e0c8c-ccb3-47ec-8fc6-4f9ef5e13d67.png)

**Comment by TTricker2** [comment]
complete
